# Generated by Django 4.0.4 on 2022-05-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
